### PR TITLE
Fix doc compilation (close #338)

### LINKED ISSUE #338: build_doc is broken
tester@edna:~/pyFAI$ python setup.py build build_doc
running build
running build_py
running build_ext
running build_scripts
running build_doc
error: [Errno 2] No such file or directory: 'gui'

### PR DESCRIPTION
**Pull request by vallsv**
But the documentation still not contains program output, while there is no more exceptions in the build_doc logs

### CODE REVIEW

**Comment by vallsv** [comment]
My bad, there is still that
```
WARNING: Unexpected return code 1 from command u'MX-calibrate --help'
reading sources... [ 30%] man/check_calib
WARNING: Unexpected return code 1 from command u'check_calib --help'
reading sources... [ 32%] man/detector2nexus
WARNING: Unexpected return code 1 from command u'detector2nexus --help'
reading sources... [ 34%] man/diff_map
WARNING: Unexpected return code 1 from command u'diff_map --help'
reading sources... [ 36%] man/diff_tomo
WARNING: Unexpected return code 1 from command u'diff_tomo --help'
reading sources... [ 39%] man/pyFAI-average
WARNING: Unexpected return code 1 from command u'pyFAI-average --help'
reading sources... [ 41%] man/pyFAI-calib
WARNING: Unexpected return code 1 from command u'pyFAI-calib --help'
reading sources... [ 43%] man/pyFAI-drawmask
WARNING: Unexpected return code 1 from command u'pyFAI-drawmask --help'
reading sources... [ 45%] man/pyFAI-integrate
WARNING: Unexpected return code 1 from command u'pyFAI-integrate --help'
reading sources... [ 47%] man/pyFAI-recalib
WARNING: Unexpected return code 1 from command u'pyFAI-recalib --help'
reading sources... [ 50%] man/pyFAI-saxs
WARNING: Unexpected return code 1 from command u'pyFAI-saxs --help'
reading sources... [ 52%] man/pyFAI-waxs
WARNING: Unexpected return code 1 from command u'pyFAI-waxs --help'
```
I will try to find the problem

**Comment by vallsv** [comment]
Result from sphinxcontrib.sourceoutput
```
$ pyFAI-integrate --help
Traceback (most recent call last):
  File "/usr/local/bin/pyFAI-integrate", line 45, in <module>
    import pyFAI, fabio
  File "/home/valls/workspace/pyfai.git/pyFAI/__init__.py", line 41, in <module>
    raise RuntimeError("Do NOT use %s from its sources: build it and use the built version" % project)
RuntimeError: Do NOT use pyFAI from its sources: build it and use the built version
```

**Comment by vallsv** [comment]
Ready for a merge

**Comment by kif** [comment]
branch has conflicts that must be resolved

**Comment by vallsv** [comment]
Fixed

**Comment by kif** [comment]
the issue is in the H5py wheel.

**Pull request merged**
