### PR TITLE
Issue 391

### PR DESCRIPTION
**Pull request by kif**
Fixes the bug found on Hurd-i386 (tested in a VM)

### CODE REVIEW

**Comment by vallsv** [comment]
It would be nice to clean up the loggging calls before merging.
```
logger.warning("Test %s from %s", foo, bar)
```
instead of
```
logger.warning("Test %s from %s" % (foo, bar))
```
There is 5 occurrences of % in the the code.
Else it looks fine.

**Comment by kif** [comment]
In general I agree with you about removing the "%".
but here it is a strange feature (due to your log suppressing code I guess):
WARNING:Test %s %s from %s
.............................................................F..FF.....F..FF.....

**Comment by vallsv** [comment]
I guess, you branch is not pulled? I fix an issue few weeks ago about that.

**Comment by kif** [comment]
On Mon, 29 Aug 2016 05:28:12 -0700
Valentin Valls <notifications@github.com> wrote:

> I guess, you branch is not pulled? I fix an issue few weeks ago about that.
indeed ...
sorry for that.
-- 
Jérôme Kieffer
tel +33 476 882 445

**Comment by vallsv** [comment]
Thats nice

**Pull request merged**
