### PR TITLE
HDF5 path compliant

### PR DESCRIPTION
**Pull request by vallsv**
This PR allow to have a full HDF5 workflow from acquisition to integration.

- Support HDF5 path on integrate
    - Support fabio URLs `h5::dataset`
    - Support silx URLs
- Support HDF5 path on integrate-gui
    - Support silx URLs
    - Support fabio URLs `h5::dataset`
    - Allow to DnD mask/dark/flat from silx view
    - Allow to load mask/dark/flat using HDF5 dialog
    - Allow to DnD the monitor name
- Support HDF5 path on calib2
    - Support silx URLs
    - Support fabio URLs `h5::dataset`
    - Allow to DnD mask from silx view
    - Allow to load mask using HDF5 dialog
- Support HDF5 path on average
    - Support fabio URLs `h5::dataset`

I try to do it from ID22 data (from P. O. Autran)
- HDF5/Nexus file from acquisition from calibant (`LaB6_60keV_380_tfout_1.h5`)
- HDF5/Nexus from acquisition from sample (`H76238.h5`)
- Plus a HDF5 containing image for mask/dark/flat (`extra_data.h5`)

Here is the recipe
```
pyFAI-average LaB6_60keV_380_tfout_1.h5::/scan_0/image/data -q 0.20-0.90 --monitor-name=/scan_0/measurement/bmon
# Generates LaB6_60keV_380_tfout_1.h5__scan_0_image_dataquantiles_1_files.edf
pyFAI-calib2 -m extra_data.h5::/mask LaB6_60keV_380_tfout_1.h5__scan_0_image_dataquantiles_1_files.edf -e 60 -c LaB6
pyFAI-calib2 # The same and load image/mask with dialog
pyFAI-calib2 # The same and DnD data from silx view
# Saves foo.poni
pyFAI-integrate # Use the dialog to load mask/flat/dark from file
pyFAI-integrate # DnD mask/flat/dark from silx view (and DnD the monitor name)
# Saves foo.json
pyFAI-integrate -j foo.json -o result.h5 H76238.h::/scan_0/image/data --no-gui
silx view result.h5
```

### CODE REVIEW

**Comment by vallsv** [comment]
The CI fail on Windows is due to fabio: here is a patch https://github.com/silx-kit/fabio/pull/291

**Comment by vallsv** [comment]
Sorry, the problem is on the `result.h5`, then on the HDF5 writer, not on fabio. I checked another thing.

**Comment by kif** [comment]
Nice piece of work

**Comment by picca** [comment]
at SOLEIL the first path in the hdf5 file change for each file.

is it possible to describe a part of the path with the NxClass type
hdf5://*:NxEntry/scan_data/...

sometimes we also have some dataset attributes which allow to identify the right data path.
long_name=something.

Cheers

Fred

**Comment by vallsv** [comment]
Oh, that's a merged branch.
The feature you are asking of could be a new issue, or maybe it is better to rename #55 in this way.

**Pull request merged**
