### PR TITLE
445 container

### PR DESCRIPTION
**Pull request by kif**
This PR defines a common container for sparse matrix initialization called ArrayBuilder. It does not (yet) provide the usage of the class in the different engines but offers good performances: for a 1k x 1M  array the cost is 186ms (104ms for python lists and  >700 for numpy arrays) then the export to CSR or LUT is <7ms.

The usage of this "ArrayBuilder" will occur only in v0.15, resulting in a huge simplification of most regriding engines.

### CODE REVIEW

**Comment by vallsv** [comment]
It would be nice to add at least a test coverage, to check if `as_CSR`, and `as_LUT` returns something.

**Comment by vallsv** [comment]
There is a conflict

**Comment by vallsv** [comment]
There is again a conflict

**Comment by kif** [comment]
I did not encounter any issue when merging...

**Comment by vallsv** [comment]
LGTM

**Pull request merged**
