### PR TITLE
1021 preproc inlined

### PR DESCRIPTION
**Pull request by kif**
First give it a try before cleaning up ...

### CODE REVIEW

**Comment by kif** [comment]
The bug was not in the inlining but rather in delta_dummy value not defined by default and check_dummy left to True by default.

**Comment by kif** [comment]
The inlined version is better from some people knowing the C better than me... so I leave it so.

**Comment by vallsv** [comment]
You could remove ` from libc.stdio cimport printf ` if everything is fixed.

**Comment by vallsv** [comment]
I clean up it, was not a big deal.
Nice catch BTW.

**Pull request merged**
