### PR TITLE
Handle the case of boolean images

### LINKED ISSUE #1829: Calib2 exception when loading boolean mask
```
WARNING:silx.gui.plot.items.image:Converting boolean image to int8 to plot it.
ERROR:pyFAI-calib2.UNCAUGHT:A numeric array is expected, but b was found.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pyFAI/gui/widgets/LoadImageToolButton.py", line 114, in __execute
    self.parent()._setValue(filename=url, data=data)
  File "/usr/lib/python3/dist-packages/pyFAI/gui/widgets/LoadImageToolButton.py", line 161, in _setValue
    model.setValue(data)
  File "/usr/lib/python3/dist-packages/pyFAI/gui/model/ImageModel.py", line 107, in setValue
    raise TypeError("A numeric array is expected, but %s was found." % value.dtype.kind)
TypeError: A numeric array is expected, but b was found.
```
Reported by @alejandrohomsp

### PR DESCRIPTION
**Pull request by kif**
close #1829

### CODE REVIEW

**Review by vallsv — APPROVED** [review]

**Comment by vallsv** [comment]
I think that's also the way it is done in silx

**Comment by vallsv** [comment]
It is maybe also working for binary without extra conversion. But your patch is costless anyway.

**Comment by kif** [comment]
> I think that's also the way it is done in silx

I copy/pasted from there ...

**Comment by kif** [comment]
Thanks for the review

**Pull request merged**
