### PR TITLE
Enable sigma_clip_legacy to be used within a worker

### LINKED ISSUE #1825: Support sigma-clipping with pixel splitting
As far as I understand the current `sigma_clip_ng` implementation does the clipping before the splitting. If you want both it should be the other way around. `sigma_clip` does in the other way around but it is not supported by the `Worker` class. It also gives a deprecation warning.

### PR DESCRIPTION
**Pull request by kif**
close #1825

### CODE REVIEW

**Review by woutdenolf — COMMENTED** [review]
I'll check asap. One potential issue that comes to mind is when you want to provide `nbpt_azim` the worker thinks the result is 2D while it is in fact 1D (see `do_2D`).

**Comment by kif** [comment]
Since `ai.sigma_clip_legagy` returns an `Integrate1dResult`, so for the `worker` it is a 1D method, despite it goes via a 2D integration: the worker does not have to be aware of it.

To configure the internal behaviour of `ai.sigma_clip_legagy`  within the worker, on can add the intermediate 2D size in the the `worker.extra_options={"npt_azim": 256, ...}`

**Comment by kif** [comment]
close #1825

**Comment by woutdenolf** [comment]
I tested and it works fine. Thanks @kif !

**Review by woutdenolf — APPROVED** [review]
LGTM

**Pull request merged**
