### PR TITLE
557 inpainting

### PR DESCRIPTION
**Pull request by kif**
Idea: perform inpainting on the 2D regrouped image to 
* paint less pixels
* take benefit of the quasi-polar symmetry.
then project back to the image geometry using bilinear interpolation.

The final step is to add noise on the inpaintied pixels using a Poissonian distribution.

Nota: this is not science, this is Photoshop.

### CODE REVIEW

**Comment by vallsv** [comment]
LGTM. Ill wait for the CI.

**Comment by vallsv** [comment]
Tests fail 2 times on Appveyor. You should investigate.

**Comment by kif** [comment]
Yep, looks like a seg-fault under windows. More work is needed !

**Comment by kif** [comment]
should be OK now...

**Comment by vallsv** [comment]
LGTM

**Pull request merged**
