### PR TITLE
fiberunit numexpr

### PR DESCRIPTION
**Pull request by EdgarGF93**

### CODE REVIEW

**Comment by EdgarGF93** [comment]
Got a x2 in speed:
```
from pyFAI.units import Unit, get_unit_fiber, to_unit
from pyFAI.integrator.azimuthal import AzimuthalIntegrator
from pyFAI.calibrant import get_calibrant
from pyFAI.integrator.fiber import FiberIntegrator
from pyFAI import detector_factory
import time
from pyFAI.gui.jupyter import subplots, display, plot2d
import matplotlib.pyplot as plt
import numpy

if __name__ == "__main__":
    ai = AzimuthalIntegrator(dist=0.1, poni1=0.1, poni2=0.1, detector=detector_factory("Eiger_4M"), wavelength=1e-10)
    fi = FiberIntegrator(dist=0.1, poni1=0.1, poni2=0.1, detector=detector_factory("Eiger_4M"), wavelength=1e-10)
    cal = get_calibrant("LaB6")
    data = cal.fake_calibration_image(ai=ai)
    qip = get_unit_fiber(name="qip_nm^-1")
    qoop = get_unit_fiber(name="qoop_nm^-1")

    t=time.perf_counter()
    res2d_fast = fi.integrate2d_grazing_incidence(data=data, unit_ip=qip, unit_oop=qoop)
    print(f"Fast path: {time.perf_counter()-t} s")
    fi.reset()

    qip.formula = None
    qip.equation = qip._equation
    qoop.formula = None
    qoop.equation = qoop._equation

    t=time.perf_counter()
    res2d_slow = fi.integrate2d_grazing_incidence(data=data, unit_ip=qip, unit_oop=qoop)
    print(f"Slow path: {time.perf_counter()-t} s")
    
    print(f"Max. diff intensity: {(res2d_slow.intensity-res2d_fast.intensity).max()}")
    print(f"Max. diff radial: {(res2d_slow.radial-res2d_fast.radial).max()}")
    print(f"Max. diff azimuthal: {(res2d_slow.azimuthal-res2d_fast.azimuthal).max()}")

```

```
Fast path: 0.6643166319990996 s
Slow path: 1.4383158040000126 s
Max. diff intensity: 0.0
Max. diff radial: 7.105427357601002e-15
Max. diff azimuthal: 0.0

```

**Comment by EdgarGF93** [comment]
can I add a script in sandbox?, it's useful for me to check that the grazing incidence results make sense

**Comment by kif** [comment]
Sandboxing scripts is OK. I would suggest to make it a notebook part of the documentation since we review the documentation for every release and ensure it keeps up to date.

**Comment by kif** [comment]
BTW, thanks for suggesting the usage of f-string for formatting formula, very clean and readable !

**Review by kif — APPROVED** [review]
LGTM

**Pull request merged**
