### PR TITLE
Feature an ImageFileDialog

### PR DESCRIPTION
**Pull request by vallsv**
This PR feature a dialog to select an 2D image from a file.

It also configure the project to configure tests and CI to be able to configure an execute Qt.

```
from pyFAI.gui.dialog.ImageFileDialog import ImageFileDialog
dialog = ImageFileDialog()
result = dialog.exec_()
if result:
    print("Selection:")
    print(dialog.selectedFile())  # path to the file
    print(dialog.selectedImage())  # numpy array
    print(dialog.selectedPath())  # path to the file with slicing
else:
    print("Nothing selected")

```

Here is a selection of a single frame EDF file:
screenshot from 2017-10-24 16 57 31

Here is a selection of a dataset from an HDF5 file:
screenshot from 2017-10-24 16 57 56

- [x] File browsing
- [x] HDF5 browsing
- [x] Merge browsing together
- [x] Display/edit the image path
- [x] Toolbar to manage history (based on history of image path)
- [x] Toolbar to manage go back action
- [x] Slicing of cube
- [x] Filter name for file formats
- [x] Use Fabio for frame selection
- [x] Select/selected URI
- [x] Save/restore dialog
- [x] Create a `silxutils` module for things we should merge in silx
- [x] Create a description of silx file formats
    - It is still not very nice
- Polish
    - [x] Clean up API
    - [x] Check return key behaviour to avoid to validate the dialog
    - [x] <del>Treeview/listview states are lost when changing model</del>
    - [x] Hide navigation icon when it is not needed
    - [x] Avoid the reset of the view of the image preview when slicing
    - [x] Display error on the GUI when loading fails
    - [x] Test (95% of coverage)
    - [x] Example
- Regression
    - [x] It is no more possible to select data from an hdf5 file, and the path is not updated
- [ ] Talk about the image URI with slicing
- Improvements (i will not have time for that)
    - [ ] Thread to open images
    - [ ] Provide sidebar shortcut inside hdf5 files (`/`, `/scan/detector/data/image`...)
    - [ ] Auto discover content of hdf5 files to provide available images
    - [ ] Allow to move the preview on an independent window

### CODE REVIEW

**Comment by vallsv** [comment]
Well, the PR is unsync, i dont know why. Here is the last branch https://github.com/vallsv/pyFAI/tree/image-dialog

**Comment by vallsv** [comment]
OMG everything pass...

**Comment by kif** [comment]
I suggest postponing this to 0.17 to release 0.16 shortly

**Comment by vallsv** [comment]
Sure

**Comment by vallsv** [comment]
Was merged on silx, and now integrated on pyFAI with #1175

**Pull request closed without merging**
