### PR TITLE
work on saving errors

### PR DESCRIPTION
**Pull request by kif**
work on issue #1286

### CODE REVIEW

**Comment by kif** [comment]
Hi Valentin,
Could you have a look on this ?

**Comment by kif** [comment]
close #1342 as well

**Comment by vallsv** [comment]
I did a fast review. Very difficult to say more as i do not have the project in mind anymore. That's small things, except the `import __main__` which is used twice. If you like a merge let me know.

**Comment by kif** [comment]
On Thu, 02 Apr 2020 02:48:15 -0700
Valentin Valls <notifications@github.com> wrote:

> I did a fast review. Very difficult to say more as i do not have the project in mind anymore. That's small things, except the `import __main__` which is used twice. If you like a merge let me know.

You review is enough. Thanks for spotting the duplicate.

**Pull request merged**
