### PR TITLE
725 calcfrom2d

### PR DESCRIPTION
**Pull request by kif**
as promised

### CODE REVIEW

**Comment by vallsv** [comment]
Is your editor auto force the typo to `'rot':-1` instead of `'rot': -1`. It looks strange, and i guess we will have a lot of conflicts between our editors.

**Comment by kif** [comment]
On Wed, 22 Nov 2017 08:19:37 +0000 (UTC)
Valentin Valls <notifications@github.com> wrote:

> Is your editor auto force the typo to `'rot':-1` instead of `'rot': -1`. It looks strange, and i guess we will have a lot of conflicts between our editors.

maybe ...

Do you suggest to enforce the use of eclipse, a specific version and the configuration file ?

**Comment by vallsv** [comment]
I would say it is better to disable auto style if it do not follow the PEP8.
Usually Eclipse provides a lot of flexibility to auto style, then maybe it is possible.

**Comment by vallsv** [comment]
LGTM

**Comment by kif** [comment]
On Wed, 22 Nov 2017 13:30:37 +0000 (UTC)
Valentin Valls <notifications@github.com> wrote:

> I would say it is better to disable auto style if it do not follow the PEP8.

To my understanding of https://www.python.org/dev/peps/pep-0008/
`"rot1": -1` is as valid as `"rot1":-1`

Apparently, Python adds the space:
>>> {'rot1':-1}
{'rot1': -1}

**Comment by vallsv** [comment]
After a coma a semi colon or anything, you have a space, that's a common English typo. `E231 missing whitespace after ':'`

**Pull request merged**
