### PR TITLE
897 config

### PR DESCRIPTION
**Pull request by kif**
add accessor for the complete geometry config.
Ideally on would replace all occurrences of get/setPyFAI with accessor to config and upgrade the geometry refinement part to serialize the datapoints.

### CODE REVIEW

**Comment by vallsv** [comment]
LGTM

**Comment by kif** [comment]
please merge

**Comment by vallsv** [comment]
LGTM

**Comment by vallsv** [comment]
The master have to be checked, this PR was merged without CI tests, cause of problem with PyOpenCL compilation.

**Pull request merged**
