### PR TITLE
Compatibility between GI and MultiGeometry

### PR DESCRIPTION
**Pull request by EdgarGF93**
- [x] MultiGeometry accepts tuple of units for integrate2d (looking at grazing-incidence)

- [x] If None, radial and azimuthal ranges are calculated and set automatically

- [x] Compatibility with gui.jupyter.plot2d

### CODE REVIEW

**Comment by EdgarGF93** [comment]
I copied some lines from Azimuthalntegrator.integrate2d about how to deal with tuple of units. Define a tuple of units all the time, by default, the azimuthal unit is TTH_DEG. If `mg.integrate1d` use the self.radial_unit, if `mg.integrate2d`, use self.unit.

**Review by mjdiff — APPROVED** [review]

**Comment by kif** [comment]
I am curious if all notebooks of the tutorial would be running fine with this modification

**Comment by EdgarGF93** [comment]
good point, it unveiled a mistake

**Comment by kif** [comment]
Edgar, to answer your question, there is no simple way to guess the radial/azimuthal range.
One could have a method that measures it, taking the bounding values for all integrators, but it is likely to take a bit of time since it needs to initialize the geometry for all AzimuthalIntegrators.

Since `MultiGeometry` is getting popular, maybe it is a good idea to create such a method and use it if the user does not provide anything sensible.

**Review by kif — APPROVED** [review]
LGTM

**Pull request merged**
