### PR TITLE
1304 hdf5plugin

### LINKED ISSUE #1304: Ensure scripts try to use hdf5plugin to access their data

### PR DESCRIPTION
**Pull request by kif**
close #1304

### CODE REVIEW

**Comment by vallsv** [comment]
I don't think it is a good idea to create an `__init__` module here.

Initializing the logging or loading library is a tricky process.

You will not be able to log early debug message this way.

The problem is not to process this way, but to not allow to process in a different way for one of the applications.

**Comment by kif** [comment]
On Wed, 15 Jan 2020 04:57:48 -0800
Valentin Valls <notifications@github.com> wrote:

> I don't think it is a good idea to create an `__init__` module here.

The __init__.py already existed, but was empty.
 
> Initializing the logging or loading library is a tricky process.

Indeed but __init__ was anyway loaded.
 
> You will not be able to log early debug message this way.

Python has an option to start in debug mode but I did not test if it was actually working. 
 
> The problem is not to process this way, but to not allow to process in a different way for one of the applications.

All applications had the same logging initialization pattern.

**Comment by vallsv** [comment]
There is a typo. `raise ImportError` have to be removed.

**Comment by kif** [comment]
On Mon, 20 Jan 2020 00:33:34 -0800
Valentin Valls <notifications@github.com> wrote:

> There is a typo. `raise ImportError` have to be removed.

:)

**Comment by vallsv** [comment]
LGTM

**Pull request merged**
