### PR TITLE
numexpr work arround

### PR DESCRIPTION
**Pull request by kif**
I am not especially happy to put in place such work around, I find it pretty ugly but something is needed while waiting for the issue to be fixed upstream.

What I did, theer is a hook to import numexpr from third_party where numexpr is locally patch (or not) to tell it not to sanitize the input. Unfortunately, this has to be done in 2 different ways, using the environment variable for `numexpr.evaluate` and patching the class for `numexpr.NumExpr`. Apparently it works. If you have a better idea, I would be happy to hear it.

### CODE REVIEW

**Comment by loichuder** [comment]
Since there is only one problematic version, would it be possible instead in the requirements of the project to disallow the version `2.8.6` of `numexpr` ?

Like putting `numexpr != 2.8.6` in `requirements.txt` and other relevant places ?

**Comment by t20100** [comment]
@loichuder proposition is a lot simpler.
Using `numexpr!=2.8.6` in `install_requires` should do the job:

https://github.com/silx-kit/pyFAI/blob/177f7dba3386ef02830f37e9f2588e4d33599efb/setup.py#L982-L991

**Comment by t20100** [comment]
> setup.py is no more used

Indeed, but the same applies for `pyproject.toml`:

https://github.com/silx-kit/pyFAI/blob/177f7dba3386ef02830f37e9f2588e4d33599efb/pyproject.toml#L39C1-L47

**Comment by kif** [comment]
Replaced by solution #1950

**Pull request closed without merging**
