### PR TITLE
Improve integrate

### LINKED ISSUE #1046: [integration] Merge processing
It exists more or less 3 different processing to integrate data whne using pyFAI as an application.

It would be good to merge everything at the same place.

As result integration GUI and CLI will use exactly the same process.

### LINKED ISSUE #1142: [diffmap] Method is invalided after the first use
I guess the fields are pop from the config, and the is no copy of the config dict.

### LINKED ISSUE #1143: [integrate] Allow to read edf and write h5
The integration process have to be reworked

But it will clean up the code a lot.

### LINKED ISSUE #1145: [integrate] Shell progress bar do not clean up it before displaying logs
As result it can create glitch like that
```
DEBUG:pyFAI:Processing H76238_raw/hc3532_POA_60keV_H76238_0154.edfA_60keV_H76238_0153.edf
```

Where `DEBUG:pyFAI:Processing H76238_raw/hc3532_POA_60keV_H76238_0154.edf` is the log and `...A_60keV_H76238_0153.edf` what part of the progress bar

### LINKED ISSUE #1150: [integration] The GUI take a very big height
It would be good to reduce the size of the GUI if possible.

- Back port ID16 groups (which allow to hide/show most used options) 
- Use a vertical scrollbar

### LINKED ISSUE #1155: [integrate] Editable geometry
Feed back from Martha

### LINKED ISSUE #1156: [integrate] Editable poni in pixels

### LINKED ISSUE #1170: [gui] Segfault when QuantityEdit widget loses focus from a QDialog
With Python3.5 and `PyQt5.11.3`.

I don't know yet why.

- Open integrate dialog
- Load a poni file
- Display the geometry dialog
- Edit a field without using return button
- Press mouse click on cancel button <segfault>

```
Program received signal SIGSEGV, Segmentation fault.
0x00007fff9eba2218 in QWidget::setFocus(Qt::FocusReason) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
(gdb) 
(gdb) bt
#0  0x00007fff9eba2218 in QWidget::setFocus(Qt::FocusReason) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#1  0x00007fff9eba2595 in QWidget::focusNextPrevChild(bool) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#2  0x00007fff9f4f4e14 in sipQDialog::focusNextPrevChild(bool) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/QtWidgets.so
#3  0x00007fff9eba24aa in QWidget::focusNextPrevChild(bool) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#4  0x00007fff9f4f3a14 in sipQTabWidget::focusNextPrevChild(bool) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/QtWidgets.so
#5  0x00007fff9eba24aa in QWidget::focusNextPrevChild(bool) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#6  0x00007fff9eba24aa in QWidget::focusNextPrevChild(bool) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#7  0x00007fff9f4f5214 in sipQWidget::focusNextPrevChild(bool) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/QtWidgets.so
#8  0x00007fff9eba2949 in QWidgetPrivate::hide_helper() () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#9  0x00007fff9eba7350 in QWidget::setVisible(bool) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#10 0x00007fff9f4c5024 in sipQWidget::setVisible(bool) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/QtWidgets.so
#11 0x00007fff9eb8c788 in QStackedLayout::setCurrentIndex(int) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#12 0x00007fff9ed1cc9f in QTabWidgetPrivate::_q_showTab(int) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#13 0x00007fff9ed1eb6f in QTabWidget::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
   from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#14 0x00007fffdde2f189 in QMetaObject::activate(QObject*, int, int, void**) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Core.so.5
#15 0x00007fff9ed001ee in QTabBar::currentChanged(int) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#16 0x00007fff9ed044af in QTabBar::setCurrentIndex(int) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#17 0x00007fff9ed06b20 in QTabBar::mousePressEvent(QMouseEvent*) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#18 0x00007fff9eba7f61 in QWidget::event(QEvent*) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#19 0x00007fff9ed04fbb in QTabBar::event(QEvent*) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#20 0x00007fff9eb6ae2c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#21 0x00007fff9eb72a13 in QApplication::notify(QObject*, QEvent*) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#22 0x00007fff9f5bc22e in sipQApplication::notify(QObject*, QEvent*) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/QtWidgets.so
#23 0x00007fffdde042d8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Core.so.5
#24 0x00007fff9eb7150f in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) ()
   from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#25 0x00007fff9ebc11dd in QWidgetWindow::handleMouseEvent(QMouseEvent*) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#26 0x00007fff9ebc3ae3 in QWidgetWindow::event(QEvent*) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#27 0x00007fff9eb6ae2c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#28 0x00007fff9eb71f60 in QApplication::notify(QObject*, QEvent*) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#29 0x00007fff9f5bc22e in sipQApplication::notify(QObject*, QEvent*) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/QtWidgets.so
#30 0x00007fffdde042d8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Core.so.5
#31 0x00007fffa1c89f6f in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
   from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Gui.so.5
#32 0x00007fffa1c8be65 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
   from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Gui.so.5
#33 0x00007fffa1c67bdb in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Gui.so.5
#34 0x00007fff9ae1c0db in QPAEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/../../lib/libQt5XcbQpa.so.5
#35 0x00007fffdde02c3a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Core.so.5
#36 0x00007fff9ed47b37 in QDialog::exec() () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#37 0x00007fff9f502905 in meth_QDialog_exec_ () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/QtWidgets.so
---Type <return> to continue, or q <return> to quit---
#38 0x00000000005a3459 in PyCFunction_Call (func=func@entry=0x7fff9b693c18, args=args@entry=0x7ffff7dff048, kwds=kwds@entry=0x0) at Objects/methodobject.c:109
#39 0x00000000004fca8d in call_function (oparg=<optimized out>, pp_stack=0x7fffffffc210) at Python/ceval.c:4705
#40 PyEval_EvalFrameEx (f=0x7fff9b53d3f8, throwflag=<optimized out>) at Python/ceval.c:3236
#41 0x00000000004fe510 in _PyEval_EvalCodeWithName (_co=0x261a450, globals=0x7fff9eec281c, locals=locals@entry=0x0, args=0x43, argcount=37904928, kws=kws@entry=0x0, 
    kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x0, qualname=0x0) at Python/ceval.c:4018
#42 0x00000000004fe5d3 in PyEval_EvalCodeEx (_co=<optimized out>, globals=<optimized out>, locals=locals@entry=0x0, args=args@entry=0x7ffff29d3ca0, 
    argcount=<optimized out>, kws=kws@entry=0x0, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0) at Python/ceval.c:4039
#43 0x000000000059e056 in function_call (func=0x7fff9b5528c8, arg=0x7ffff29d3c88, kw=0x0) at Objects/funcobject.c:627
#44 0x0000000000437c6e in PyObject_Call (func=func@entry=0x7fff9b5528c8, arg=arg@entry=0x7ffff29d3c88, kw=kw@entry=0x0) at Objects/abstract.c:2165
#45 0x000000000059133d in method_call (func=0x7fff9b5528c8, arg=0x7ffff29d3c88, kw=0x0) at Objects/classobject.c:330
#46 0x0000000000437c6e in PyObject_Call (func=func@entry=0x7ffff6ef5788, arg=arg@entry=0x7ffff7dff048, kw=<optimized out>) at Objects/abstract.c:2165
#47 0x00000000004f4b27 in PyEval_CallObjectWithKeywords (func=0x7ffff6ef5788, arg=0x7ffff7dff048, kw=<optimized out>) at Python/ceval.c:4580
#48 0x00007fffe080aaf5 in PyQtSlot::call(_object*, _object*) const () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/QtCore.so
#49 0x00007fffe080b000 in PyQtSlot::invoke(void**, _object*, void*, bool) const () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/QtCore.so
#50 0x00007fffe080b27b in PyQtSlotProxy::unislot(void**) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/QtCore.so
#51 0x00007fffe080c267 in PyQtSlotProxy::qt_metacall(QMetaObject::Call, int, void**) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/QtCore.so
#52 0x00007fffdde2f2f4 in QMetaObject::activate(QObject*, int, int, void**) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Core.so.5
#53 0x00007fff9ec4f3a2 in QAbstractButton::clicked(bool) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#54 0x00007fff9ec4f5a4 in QAbstractButtonPrivate::emitClicked() () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#55 0x00007fff9ec5113e in QAbstractButtonPrivate::click() () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#56 0x00007fff9ec51295 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#57 0x00007fff9ed2fd5a in QToolButton::mouseReleaseEvent(QMouseEvent*) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#58 0x00007fff9f523dc3 in sipQToolButton::mouseReleaseEvent(QMouseEvent*) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/QtWidgets.so
#59 0x00007fff9eba7688 in QWidget::event(QEvent*) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#60 0x00007fff9ed2fe29 in QToolButton::event(QEvent*) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#61 0x00007fff9f524483 in sipQToolButton::event(QEvent*) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/QtWidgets.so
#62 0x00007fff9eb6ae2c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#63 0x00007fff9eb72a13 in QApplication::notify(QObject*, QEvent*) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#64 0x00007fff9f5bc22e in sipQApplication::notify(QObject*, QEvent*) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/QtWidgets.so
#65 0x00007fffdde042d8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Core.so.5
#66 0x00007fff9eb7150f in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) ()
   from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#67 0x00007fff9ebc11dd in QWidgetWindow::handleMouseEvent(QMouseEvent*) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#68 0x00007fff9ebc3ae3 in QWidgetWindow::event(QEvent*) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#69 0x00007fff9eb6ae2c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#70 0x00007fff9eb71f60 in QApplication::notify(QObject*, QEvent*) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
#71 0x00007fff9f5bc22e in sipQApplication::notify(QObject*, QEvent*) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/QtWidgets.so
#72 0x00007fffdde042d8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Core.so.5
#73 0x00007fffa1c89f6f in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
   from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Gui.so.5
#74 0x00007fffa1c8be65 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
   from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Gui.so.5
#75 0x00007fffa1c67bdb in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Gui.so.5
---Type <return> to continue, or q <return> to quit---
#76 0x00007fff9ae1c0db in QPAEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/../../lib/libQt5XcbQpa.so.5
#77 0x00007fffdde02c3a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Core.so.5
#78 0x00007fffdde0b640 in QCoreApplication::exec() () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5Core.so.5
#79 0x00007fff9f447800 in meth_QApplication_exec_ () from /home/valls/.local/lib/python3.5/site-packages/PyQt5/QtWidgets.so
#80 0x00000000005a3459 in PyCFunction_Call (func=func@entry=0x7fff9b58ffc0, args=args@entry=0x7ffff7dff048, kwds=kwds@entry=0x0) at Objects/methodobject.c:109
#81 0x00000000004fca8d in call_function (oparg=<optimized out>, pp_stack=0x7fffffffd490) at Python/ceval.c:4705
#82 PyEval_EvalFrameEx (f=0x19d8338, throwflag=<optimized out>) at Python/ceval.c:3236
#83 0x00000000004fe510 in _PyEval_EvalCodeWithName (_co=0x261a450, globals=0x7fff9eec281c, locals=locals@entry=0x0, args=0x3, argcount=37904928, argcount@entry=2, 
    kws=0x0, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x7fffefe446b0, qualname=0x7fffefe446b0) at Python/ceval.c:4018
#84 0x00000000004fb6fc in fast_function (nk=<optimized out>, na=2, n=<optimized out>, pp_stack=0x7fffffffd670, func=0x7fffefe421e0) at Python/ceval.c:4813
#85 call_function (oparg=<optimized out>, pp_stack=0x7fffffffd670) at Python/ceval.c:4730
#86 PyEval_EvalFrameEx (f=f@entry=0xe81438, throwflag=throwflag@entry=0) at Python/ceval.c:3236
#87 0x00000000004fc862 in fast_function (nk=<optimized out>, na=1, n=1, pp_stack=0x7fffffffd770, func=0x7fffea315f28) at Python/ceval.c:4803
#88 call_function (oparg=<optimized out>, pp_stack=0x7fffffffd770) at Python/ceval.c:4730
#89 PyEval_EvalFrameEx (f=f@entry=0x7ffff39599a8, throwflag=throwflag@entry=0) at Python/ceval.c:3236
#90 0x00000000004fc862 in fast_function (nk=<optimized out>, na=0, n=0, pp_stack=0x7fffffffd870, func=0x7fffea31a048) at Python/ceval.c:4803
#91 call_function (oparg=<optimized out>, pp_stack=0x7fffffffd870) at Python/ceval.c:4730
#92 PyEval_EvalFrameEx (f=f@entry=0xe9c608, throwflag=throwflag@entry=0) at Python/ceval.c:3236
#93 0x00000000004fc862 in fast_function (nk=<optimized out>, na=2, n=2, pp_stack=0x7fffffffd970, func=0x7ffff646fd08) at Python/ceval.c:4803
#94 call_function (oparg=<optimized out>, pp_stack=0x7fffffffd970) at Python/ceval.c:4730
#95 PyEval_EvalFrameEx (f=0x9553b8, throwflag=<optimized out>) at Python/ceval.c:3236
#96 0x00000000004fe510 in _PyEval_EvalCodeWithName (_co=0x261a450, _co@entry=0x7ffff6de7930, globals=0x7fff9eec281c, globals@entry=0x7ffff6d90450, locals=0x0, 
    locals@entry=0x7ffff6d90450, args=0x40, argcount=37904928, argcount@entry=0, kws=kws@entry=0x0, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x0, 
    qualname=0x0) at Python/ceval.c:4018
#97 0x00000000004fe5ff in PyEval_EvalCodeEx (closure=0x0, kwdefs=0x0, defcount=0, defs=0x0, kwcount=0, kws=0x0, argcount=0, args=0x0, locals=locals@entry=0x7ffff6d90450, 
    globals=globals@entry=0x7ffff6d90450, _co=_co@entry=0x7ffff6de7930) at Python/ceval.c:4039
#98 PyEval_EvalCode (co=co@entry=0x7ffff6de7930, globals=globals@entry=0x7ffff6eb6688, locals=locals@entry=0x7ffff6eb6688) at Python/ceval.c:777
#99 0x000000000052a1de in run_mod (arena=0x9c1f60, flags=0x7fffffffdc10, locals=0x7ffff6eb6688, globals=0x7ffff6eb6688, filename=0x7ffff6d90450, mod=0x9f0610)
    at Python/pythonrun.c:976
#100 PyRun_FileExFlags (fp=0x9553a0, filename_str=<optimized out>, start=<optimized out>, globals=0x7ffff6eb6688, locals=0x7ffff6eb6688, closeit=1, flags=0x7fffffffdc10)
    at Python/pythonrun.c:929
#101 0x000000000052a3dc in PyRun_SimpleFileExFlags (fp=0x9553a0, filename=0x7ffff6d95bd8 "/workspace/valls/pyfai.git/bootstrap.py", closeit=1, flags=0x16)
    at Python/pythonrun.c:396
#102 0x0000000000420c73 in run_file (p_cf=0x7fffffffdc10, filename=0x8ee2e0 L"/workspace/valls/pyfai.git/bootstrap.py", fp=0x9553a0) at Modules/main.c:318
#103 Py_Main (argc=argc@entry=6, argv=argv@entry=0x8ed010) at Modules/main.c:768
#104 0x000000000041c617 in main (argc=6, argv=<optimized out>) at ./Programs/python.c:65

```

### PR DESCRIPTION
**Pull request by vallsv**
- Support multiframe/fileseries/h5 as input
- Support h5 as output
- Support `h5::entrypath` as output
- Fix progress bar display (logging message are displayed over it)
- Support monitor from HDF5
- Statistics on processing
- Check resulting NXdata (1d integration + error and 2d integration are displayable with `silx view`)
- Fix problem of "hdf5 output already exists" (introduce command line options `--delete` (delete the file) `--overwrite` (overwrite the NXentry path)  `--append` (create a new NXentry)
- Integrating GUI allow allow to edit the geometry (the fid2d geometry is also editable)
- Integrating GUI uses now a scrollbar to allow to reduce the height of the window.

Closes #1142
Closes #1155
Closes #1156
Closes #1150
Closes #1145
Closes #1046
Closes #1145
Closes #1143 
Closes #1170

### CODE REVIEW

**Comment by vallsv** [comment]
Here is the kind of log displayed at the end of the integration
```
INFO:pyFAI:[First frame] Preprocessing time: 2423ms                                            
INFO:pyFAI:[Per frames] Reading time: 48ms; Processing time: 270ms
INFO:pyFAI:[Total] Reading time: 0.096s; Processing time: 2.963s
INFO:pyFAI:Execution done in 3.263s !
```

**Comment by vallsv** [comment]
They are still issues for missing things #1044, #1173, #1174

**Comment by vallsv** [comment]
But i think it is good enough to be merged.

**Comment by kif** [comment]
looks cool !

**Pull request merged**
