### PR TITLE
Enable Python3.7 + enable remote desktop

### PR DESCRIPTION
**Pull request by kif**
Please refer to:
https://ci.appveyor.com/project/ESRF/silx/settings/environment
to retrieve the remote desktop password and in the logs to get the IP address of the VM

### CODE REVIEW

**Comment by vallsv** [comment]
Problem with Python 3.7 on Windows. See https://bugs.python.org/issue34251

Maybe the python 3.7 installed on appveyor still contain this bug

**Comment by vallsv** [comment]
Python 3.7.1 should be release around 2018-10-06

**Comment by vallsv** [comment]
Appveyor still using Python 3.7.0

**Comment by kif** [comment]
Follow on:
https://github.com/appveyor/ci/issues/2735

**Comment by kif** [comment]
apparently on must change the version of VS used to 2017

**Comment by kif** [comment]
Hia-hou !!!
Enforcing the new  compiler helps definitively

**Comment by vallsv** [comment]
Congratulation

**Pull request merged**
