### PR TITLE
serialize worker config and deserialize as azimuthal integrator

### LINKED ISSUE #1991: Detector info is not restored when loading `pyFAI-diffmap` configuration
`pyFAI-diffmap` stores a configuration in the output HDF5 file but this configuration cannot be used to restore the geometry (the detector definition is missing:
```
{'unit': 'q_nm^-1',
 'dist': 0.1999693237019301,
 'poni1': 0.12279243634743776,
 'poni2': 0.11803581502718556,
 'rot1': 0.013977781483742164,
 'rot3': -7.470130596383977e-05,
 'rot2': -0.013837145398466972,
 'pixel1': 7.5e-05,
 'pixel2': 7.5e-05,
 'splineFile': None,
 'wavelength': 3.7380000000000004e-11,
 'nbpt_azim': 1,
 'nbpt_rad': 5000,
 'polarization_factor': 0.99,
 'dummy': None,
 'delta_dummy': None,
 'correct_solid_angle': True,
 'dark_current_image': None,
 'flat_field_image': None,
 'mask_image': 'DAC-04-mask.npy',
 'error_model': 'poisson',
 'shape': [3262, 3108],
 'method': [1, 'full', 'csr', 'opencl', 'gpu'],
 'do_azimuth_range': False,
 'do_radial_range': False}
```

### PR DESCRIPTION
**Pull request by kif**
Close #1991 
For now: 
- [X] load old config
- [x] test reload
- [X] Fix the worker.get_config()

### CODE REVIEW

**Comment by kif** [comment]
@loichuder can you check it works for you ?

**Comment by loichuder** [comment]
Nope, it doesn't work.

```
>>> json_config = json.loads(config)
>>> json_config
{'unit': '2th_deg', 'dist': 0.18352000680503333, 'poni1': 0.13032588094799352, 'poni2': 0.11127533501437878, 'rot1': 0.014561540164214496, 'rot3': 2.1944567622347524e-09, 'rot2': -0.010992447540998289, 'pixel1': 7.5e-05, 'pixel2': 7.5e-05, 'splineFile': None, 'wavelength': 3.7380000000000004e-11, 'nbpt_azim': 1, 'nbpt_rad': 2000, 'polarization_factor': None, 'dummy': None, 'delta_dummy': None, 'correct_solid_angle': True, 'dark_current_image': None, 'flat_field_image': None, 'mask_image': None, 'error_model': 'poisson', 'shape': [3262, 3108], 'method': [1, 'bbox', '*', '*', None], 'do_azimuth_range': False, 'do_radial_range': False}
>>> ai = pyFAI.load(json_config)
>>> ai.detector
Undefined detector
```

**Comment by kif** [comment]
```
json_config = {'unit': '2th_deg', 'dist': 0.18352000680503333, 'poni1': 0.13032588094799352, [...] }
import pyFAI
import pyFAI.worker
 w = pyFAI.worker.Worker()
w.set_config(json_config)
ai = w.ai
ai.detector
```
does work

**Comment by loichuder** [comment]
Not for me:

```
In [6]: worker.set_config(json_config)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[6], line 1
----> 1 worker.set_config(json_config)

File ~/Projects/pyFAI/build/lib/python3.10/site-packages/pyFAI/worker.py:454, in Worker.set_config(self, config, consume_keys)
    450 if not consume_keys:
    451     # Avoid to edit the input argument
    452     config = dict(config)
--> 454 integration_config.normalize(config, inplace=True)
    455 _init_ai(self.ai, config, consume_keys=True, read_maps=False)
    457 # Do it here before reading the AI to be able to catch the io

File ~/Projects/pyFAI/build/lib/python3.10/site-packages/pyFAI/io/integration_config.py:176, in normalize(config, inplace, do_raise)
    174 version = config["version"]
    175 if version == 2:
--> 176     _patch_v2_to_v3(config)
    178 application = config.get("application", None)
    179 if application != "pyfai-integrate":

File ~/Projects/pyFAI/build/lib/python3.10/site-packages/pyFAI/io/integration_config.py:151, in _patch_v2_to_v3(config)
    146 """Rework the config dictionary from version 2 to version 3
    147 
    148 :param dict config: Dictionary reworked inplace.
    149 """
    150 old_method = config.pop("method")
--> 151 method = method_registry.Method.parsed(old_method)
    152 config["method"] = method.split, method.algo, method.impl
    153 config["opencl_device"] = method.target

File ~/Projects/pyFAI/build/lib/python3.10/site-packages/pyFAI/method_registry.py:111, in Method.parsed(string)
    109 impl = "*"
    110 split = "*"
--> 111 string = string.lower()
    113 if "lut" in string:
    114     algo = "lut"

AttributeError: 'list' object has no attribute 'lower'
```

I also get the same error when running the tests.

**Comment by loichuder** [comment]
I was using the silx branch https://github.com/silx-kit/pyFAI/tree/1991_worker_config instead of your branch https://github.com/kif/pyFAI/tree/1991_worker_config.

It works :+1:

**Pull request merged**
