### PR TITLE
Rework the picking task

### LINKED ISSUE #872: [calib2] Improve peak picking
Feedback from the current peak picking screen allow us to to think about improvements

- Names are not used, it should be removed
    - Management should be done per rings
- Improve tools when the picking fails
    - Allow to manually remove peaks
    - If possible never lose user picking (nevertheless it is requested)
- Improve tools in case of dotted rings
- Improve identification of the rings in the screen
    - Ring numbers could be displayed on the screen
    - Improve the contrast between colors
- Allow an easier auto-extraction of rings
    - Re-extract already picked rings
    - Extract more rings, which is really an often used feature
    - Extract all, which could extract all the rings theoretically displayed on the image
    - Extract from...to, maybe, more or else current implementation
- Relabel, disable a ring

### Prototype

Screenshot from 2019-03-11 16-28-32

### PR DESCRIPTION
**Pull request by vallsv**
- Main interaction
    - [x] Allow to pick coords to an existing group
    - [x] Implement the ring selection
    - [x] Implement extraction of a single ring
    - [x] Implement extraction of all existing rings
    - [x] Implement extraction of more rings
    - [x] Tool to remove peaks (brush interaction, if possible)
    - [x] Tool to clean up picked rings
    - [x] Allow to disable a ring
    - [x] Allow to hi-light a ring
- Not needed to test the main rework with users
    - [x] Implement extraction of all reachable rings
    - [x] Tool to relabel peaks
    - [x] Tooltips over the peaks
    - [x] Improve memory consumption (use non-mutable coord list)
- Polishing
    - [x] Check location of peak marker on the image pixels
    - [x] Ring color should depend on ring number
    - [x] Maybe tune the mouse cursor according to the brush/erasor
    - [x] Key shortcut for rings numbers
    - [x] Avoid interaction when extraction
    - [ ] <s>Use 0-indexed rings</s> (too dangerous now, not much time)
    - [ ] <s> Display the ring color within the spinner widget</s>
    - [x] Using a pen tool, then go back to default zoom tools fail
    - [x] Choose a better colors for the rings
    - [x] Remove the warning `ERROR:pyFAI.massif:You picked a background point at`
    - [x] Remove the warning `No diffraction image available => not showing the contour`
    - [x] Remove `_DummyStdOut`

Closes #872

### CODE REVIEW

**Comment by vallsv** [comment]
The rework is not finished, but this PR already allow to test the new behaviour to create and edit rings. If you like to test it.

**Comment by vallsv** [comment]
The PR contains now all the expected features. It could be tested.

**Comment by vallsv** [comment]
It could be merged now, if you like.
But it also can wait for a week. It's fine.
I would like to pass some user tests.

**Comment by vallsv** [comment]
Have to be fixed
```
Traceback (most recent call last):
  File "/workspace/valls/env/pyfai/lib/python3.5/site-packages/pyFAI/gui/tasks/PeakPickingTask.py", line 1115, in __loadPeaksFromFile
    _logger.error(e.args[0])
IndexError: tuple index out of range
```

**Comment by vallsv** [comment]
```
ERROR:pyFAI-calib2.UNCAUGHT:To change to a dtype of a different size, the array must be C-contiguous
Traceback (most recent call last):
  File "/workspace/valls/env/pyfai/lib/python3.5/site-packages/pyFAI/gui/tasks/PeakPickingTask.py", line 1400, in __onPickPicked
    peak.mergeCoords(peakModel)
  File "/workspace/valls/env/pyfai/lib/python3.5/site-packages/pyFAI/gui/model/PeakModel.py", line 140, in mergeCoords
    previous_coords = self.__coords.view(dtype)
ValueError: To change to a dtype of a different size, the array must be C-contiguous
```

**Comment by vallsv** [comment]
Infinite look while fitting
```WARNING:bilinear:negative index along dim1: f1= -inf```

**Comment by kif** [comment]
I got this in debbian9
```
ERROR:pyFAI-calib2.UNCAUGHT:'QAction' object has no attribute 'setShortcutVisibleInContextMenu'
Traceback (most recent call last):
  File "/usr/bin/pyFAI-calib2", line 11, in <module>
    load_entry_point('pyFAI==0.18.0a1', 'console_scripts', 'pyFAI-calib2')()
  File "/usr/lib/python3/dist-packages/pyFAI/app/calib2.py", line 566, in main
    window = CalibrationWindow(context)
  File "/usr/lib/python3/dist-packages/pyFAI/gui/CalibrationWindow.py", line 154, in __init__
    self.__tasks = self.createTasks()
  File "/usr/lib/python3/dist-packages/pyFAI/gui/CalibrationWindow.py", line 249, in createTasks
    PeakPickingTask(),
  File "/usr/lib/python3/dist-packages/pyFAI/gui/tasks/AbstractCalibrationTask.py", line 48, in __init__
    self._initGui()
  File "/usr/lib/python3/dist-packages/pyFAI/gui/tasks/PeakPickingTask.py", line 986, in _initGui
    toolBar = self.__createMainRingToolBar()
  File "/usr/lib/python3/dist-packages/pyFAI/gui/tasks/PeakPickingTask.py", line 1194, in __createMainRingToolBar
    action.setShortcutVisibleInContextMenu(True)
AttributeError: 'QAction' object has no attribute 'setShortcutVisibleInContextMenu'
```

**Comment by vallsv** [comment]
Are you still using PyQt4?

It could be removed anyway, there is no context menu here.

**Comment by vallsv** [comment]
I updated the PR

**Comment by kif** [comment]
Works for me ...

**Pull request merged**
