### PR TITLE
1129 open cl histogram rebased2

### LINKED ISSUE #1129: [integration] OpenCL + histogram not implemented
Could be implemented

### PR DESCRIPTION
**Pull request by kif**
First of its kind: OpenCL integrator focused on new integration scheme
close #1129

### CODE REVIEW

**Comment by vallsv** [comment]
LGTM, but maybe you should ask a review from Pierre?

**Comment by kif** [comment]
On Tue, 19 Mar 2019 01:21:07 -0700
Valentin Valls <notifications@github.com> wrote:

> vallsv approved this pull request.
> 

There is still smth fishy due to the dependency of int64 atomic...

**Comment by kif** [comment]
This engine is working as expected (I did not yet test it with the "variance" test)

**Comment by vallsv** [comment]
LGTM

BTW, if the tex file was converted to rst it is i think better to remove it.

**Pull request merged**
