### PR TITLE
UnitFiber class

### PR DESCRIPTION
**Pull request by EdgarGF93**
New class UnitFiber to handle units for grazing-incidence and fiber diffraction
UnitFiber is a child of Unit with methods set_incident_angle and set_tilt_angle

We can access the units for fiber diffraction with methods to change the angles with the method **pyFAI.units.get_unit_fiber**

### CODE REVIEW

**Comment by EdgarGF93** [comment]
Example:
```
from pyFAI.gui import jupyter
from pyFAI.test.utilstest import UtilsTest
import fabio
from pyFAI import load
from pyFAI.units import get_unit_fiber

data = fabio.open(UtilsTest.getimage("pm6.edf")).data
ai = load(UtilsTest.getimage("lab6_pm6.poni"))
INCIDENT_ANGLE = 0.1
TILT_ANGLE = 0.2
unit_qip = get_unit_fiber(name="qiprot90_nm^-1", incident_angle=INCIDENT_ANGLE, tilt_angle=TILT_ANGLE)
unit_qoop = get_unit_fiber(name="qooprot90_nm^-1", incident_angle=INCIDENT_ANGLE, tilt_angle=TILT_ANGLE)

qip = ai.array_from_unit(unit=unit_qip)
qoop = ai.array_from_unit(unit=unit_qoop)
method=("no", "csr", "cython")
res2d = ai.integrate2d(data, 1000,1000, unit=(unit_qip, unit_qoop), method=method)

jupyter.plot2d(res2d)
pass
```
image

**Comment by EdgarGF93** [comment]
Removed rot90 units and add **sample_orientation** parameter

```
from pyFAI.gui import jupyter
from pyFAI.test.utilstest import UtilsTest
import fabio
from pyFAI import load
from pyFAI.units import get_unit_fiber

data = fabio.open(UtilsTest.getimage("pm6.edf")).data
ai = load(UtilsTest.getimage("lab6_pm6.poni"))
INCIDENT_ANGLE = 0.0
TILT_ANGLE = 0.0
SAMPLE_ORIENTATION = 1
unit_qip = get_unit_fiber(name="qip_nm^-1", incident_angle=INCIDENT_ANGLE, tilt_angle=TILT_ANGLE, sample_orientation=SAMPLE_ORIENTATION)
unit_qoop = get_unit_fiber(name="qoop_nm^-1", incident_angle=INCIDENT_ANGLE, tilt_angle=TILT_ANGLE, sample_orientation=SAMPLE_ORIENTATION)

method=("no", "csr", "cython")
res2d = ai.integrate2d(data, 1000,1000, unit=(unit_qip, unit_qoop), method=method)

jupyter.plot2d(res2d)
pass
```
image
```
fig, axes = jupyter.subplots(ncols=4, figsize=(20,5))
for ind in range(1,5):
    ai.reset()
    unit_qip.set_sample_orientation(ind)
    unit_qoop.set_sample_orientation(ind)
    res2d = ai.integrate2d(data, 1000,1000, unit=(unit_qip, unit_qoop), method=method)
    jupyter.plot2d(res2d, ax=axes[ind-1])
    pass
```
image

**Comment by EdgarGF93** [comment]
- [ ] Two methods for fiber integration: integrate_fiber and integrate_grazing_incidence (+ incident ang tilt angle)

- [ ] Updated tutorial

**Review by kif — APPROVED** [review]
LGTM ...
One concern: what if the user performs an integration with one incidence/tilt, then changes the value. No cache would be invalidated. This should be fixed, maybe in another PR.
```
In [2]: import pyFAI.units

In [3]: pyFAI.units.get_unit_fiber("qip_nm^-1",1,2)
Out[3]: qip_nm^-1

In [4]: u1 = pyFAI.units.get_unit_fiber("qip_nm^-1",1,2)

In [5]: u2 = pyFAI.units.get_unit_fiber("qip_nm^-1",2,3)

In [6]: u1.incident_angle
Out[6]: 2

In [7]: u2.incident_angle
Out[7]: 2

In [8]: import copy

In [9]: u1c=copy.copy(u1)

In [10]: u1c.set_incident_angle(1)

In [11]: u1c.incident_angle
Out[11]: 1

In [12]: u2.incident_angle
Out[12]: 2
```

**Pull request merged**
