### PR TITLE
Use ellipse to guess poni on geometry refinment

### LINKED ISSUE #541: Enhance ControlPoints class for interactive use (jupyter)

### PR DESCRIPTION
**Pull request by vallsv**
close #541
Conflicts:
	pyFAI/peak_picker.py

typo
Conflicts:
	pyFAI/geometry.py

Refine the test:
relax elder test and make a very precise on on synthetic data.
fix the guessed ellipse.

Typo on length

fix typo
Conflicts:
	pyFAI/geometryRefinement.py

switch to 3-letter labels
Conflicts:
	pyFAI/peak_picker.py

Allow the construction of the GeometryRefinement without data

### CODE REVIEW

**Comment by vallsv** [comment]
This failure looks to occur often:
```
FAIL: test_python (pyFAI.test.test_preproc.TestPreproc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\pyfai\build\lib.win-amd64-3.5\pyFAI\test\test_preproc.py", line 125, in test_python
    self.one_test(python_preproc)
  File "C:\projects\pyfai\build\lib.win-amd64-3.5\pyFAI\test\test_preproc.py", line 114, in one_test
    self.assertGreater(abs(numpy.round(res) - target).max(), 0, "flat != solidangle")
AssertionError: 0.0 not greater than 0 : flat != solidangle
```

**Comment by vallsv** [comment]
```
FAIL: test_python (pyFAI.test.test_preproc.TestPreproc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\pyfai\build\lib.win-amd64-2.7\pyFAI\test\test_preproc.py", line 125, in test_python
    self.one_test(python_preproc)
  File "C:\projects\pyfai\build\lib.win-amd64-2.7\pyFAI\test\test_preproc.py", line 114, in one_test
    self.assertGreater(abs(numpy.round(res) - target).max(), 0, "flat != solidangle")
AssertionError: flat != solidangle
```

**Comment by kif** [comment]
This has nothing to do with this commit: it is a weakness in the test suite.
The flat is checked for dummies, not the solid_angle array and as we test with random values ...
Maybe we should set the dummies to <<0 values

**Comment by kif** [comment]
This is not yet complete but it kind-of works...
the tilt calculation is not yet correct.

**Pull request merged**
