### PR TITLE
Move ImageD11 conversion to an extra sub-module

### PR DESCRIPTION
**Pull request by kif**
This PR tries to address the issues raised in #2079 
- [X] move the ImageD11 conversion code to another submodule 
- [X] Allow the user to select the unit for wavelength and distances (pixel size, sample-detector distance)
- [ ] Use the orientation feature to replace the orientation matrix
- [x] re-wire this new module in pyFAI.geometry (to maintain current API)
- [x] Provide some tests ensuring `ImageD11` and `pyFAI` provide the same geometrical positions

### CODE REVIEW

**Comment by kif** [comment]
There is one feature which is not yet implemented (or checked). 
@jonwright maybe we can agree to merge the PR as it is, or closely, and create a new issue + PR to address the change of orientation of the detector ?

**Comment by jonwright** [comment]
Hi Jerome - 
As you can imagine, I spent all my time yak shaving to work out how to look at the branch install and still didn't figure out how to test this against ImageD11 (git). It looks fine to merge by reading it. We just need to add another "feature" to handle the distortion as dxfile+dyfile in here or as a nexus file over in ImageD11. Probably better to fix ImageD11 to read those. 
The "off by 0.5 pixels" is expected, so should be fixable in the test.
I will try to look at the Eiger versus Frelon flips and come up with something for the conversion.
Thanks!
Jon

**Review by jonwright — APPROVED** [review]
OK  to merge - I will aim to come back with a pull request if I find a problem, and it is easier for me to figure out how to do git if this is merged!

**Comment by kif** [comment]
There is this new bug for reminding to fix the orientation. Everything else looks OK.

**Pull request merged**
