### PR TITLE
scipy 1.0 beta

### PR DESCRIPTION
**Pull request by kif**
test using scipy v1.0 beta instead of the one provided by wheelhouse of silx

### CODE REVIEW

**Comment by kif** [comment]
close #704

**Comment by vallsv** [comment]
```
Traceback (most recent call last):
  File "run_tests.py", line 425, in <module>
    unittest.defaultTestLoader.loadTestsFromNames(options.test_name))
  File "c:\python27-x64\Lib\unittest\loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "c:\python27-x64\Lib\unittest\loader.py", line 115, in loadTestsFromName
    test = obj()
  File "C:\projects\pyfai\build\lib.win-amd64-2.7\pyFAI\test\__init__.py", line 50, in suite
    from . import test_all
  File "C:\projects\pyfai\build\lib.win-amd64-2.7\pyFAI\test\test_all.py", line 57, in <module>
    from . import test_distortion
  File "C:\projects\pyfai\build\lib.win-amd64-2.7\pyFAI\test\test_distortion.py", line 46, in <module>
    from .. import distortion
  File "C:\projects\pyfai\build\lib.win-amd64-2.7\pyFAI\distortion.py", line 67, in <module>
    v = tuple(int(i) for i in scipy.version.short_version.split("."))
  File "C:\projects\pyfai\build\lib.win-amd64-2.7\pyFAI\distortion.py", line 67, in <genexpr>
    v = tuple(int(i) for i in scipy.version.short_version.split("."))
ValueError: invalid literal for int() with base 10: '0rc1'
```

**Comment by kif** [comment]
why is the last commit not added in the PR ?

**Comment by kif** [comment]
chair-keyboard interface error

**Pull request merged**
