### PR TITLE
3D visualization of detector

### PR DESCRIPTION
**Pull request by vallsv**
- [x] Icon for the action
- [x] Button to close
- [x] Process widget to wait for loading
- [x] Use the geometry to display detector/ray/sample

### CODE REVIEW

**Comment by kif** [comment]
I have this error regardless if I am using python 2 or 3 ...
```
ERROR:pyFAI-calib2.UNCAUGHT:type object 'StandardButton' has no attribute 'Cancel'
Traceback (most recent call last):
  File "/users/kieffer/workspace-400/pyFAI/build/lib.linux-x86_64-3.5/pyFAI/gui/tasks/ExperimentTask.py", line 118, in __display3dDialog
    dialog = Detector3dDialog(self)
  File "/users/kieffer/workspace-400/pyFAI/build/lib.linux-x86_64-3.5/pyFAI/gui/dialog/Detector3dDialog.py", line 267, in __init__
    self.__buttons.addButton(qt.QDialogButtonBox.StandardButton.Cancel)
AttributeError: type object 'StandardButton' has no attribute 'Cancel'
```

**Comment by kif** [comment]
To generate the 3D array using Thomas's method I suggest using:
```
zyx = ai.calc_pos_zyx(corners=True)
xyz = numpy.zeros(zyx[0].shape+(3,))
xyz[...,0] = zyx[2]
xyz[...,1] = zyx[1]
xyz[...,2] = zyx[0]
plus = numpy.array([0,0,1,2,3,3])
idx = (numpy.atleast_2d(4*numpy.arange(zyx[0].size)).T+plus).ravel()
```
This takes 3s for a 16Mpix image.

**Comment by vallsv** [comment]
The Qt widget is fixed. For the interleaved fans, primitives are not yet available.

**Comment by vallsv** [comment]
I rebase the thing with the numpy 1.16 patch

**Comment by vallsv** [comment]
I will check that, but It have nothing to do with this PR

**Comment by kif** [comment]
yep works !

**Comment by alexmarie78** [comment]
Hello, I'd like to try the 3D-preview, but after cloning the repository, I can't manage to find the 3D-preview button.
How should I do to try 3D-preview ?

**Comment by vallsv** [comment]
screenshot from 2019-01-17 14-37-57

Here it is.
It is not an incredible thing, but it could help.
I think i will add this icon to the geometry fitting too.

**Comment by vallsv** [comment]
From your git repository you can also use
```
python ./bootstrap.py pyFAI-calib2
```

**Comment by alexmarie78** [comment]
Hello,
I'm trying 3D-preview with the CirPad detector and I get this error : 

`ERROR:pyFAI.gui.dialog.Detector3dDialog:incompatible shape for a non-contiguous array`

Does it mean something for you ?

**Comment by alexmarie78** [comment]
Tried to find "incompatible" in the pyFAI source code, but couldn't find anything.
Is it possible to add the line in the error message ?

**Comment by alexmarie78** [comment]
The pixels.shape of the CirPad is (11200, 120, 4, 3) and the problem occurs at line 127 of Detector3dDialog.py when `pixels.shape = -1, 4, 3` is called.

**Comment by alexmarie78** [comment]
Seems like replacing `pixels.shape = -1, 4, 3` by : `pixels = numpy.reshape(pixels,(-1, 4, 3))` works.
Do you want a PR ?

**Comment by vallsv** [comment]
If it is convenient for you, feel free to provide a PR. I will merge it.

I have to ask @kif but i am pretty sure it would be better to align the array before, if it is not yet the case: on the CirPad `get_pixel_corners`, as i don't know if it is yet the case.

Please feel free to open an issue next time. It is more easy to manage.

**Comment by vallsv** [comment]
BTW for the CirPad, the 3D initialization is very very slow. That is known, and i hope it will be fixed soon.

**Pull request merged**
