### PR TITLE
601 flatfield

### PR DESCRIPTION
**Pull request by kif**
This PR looks strange ... all changes from #606 re-appear :(

Only azimuthal integrator and detectors have been actually modified.

### CODE REVIEW

**Comment by kif** [comment]
close #601

**Comment by vallsv** [comment]
I can't merge while 2 PR are all-together. If i merge this one, it's like merging metadata. We can try to clean up it together if you like. Or maybe merge metadata and flatfield in a single PR.

**Comment by kif** [comment]
OK I will merge this PR into the "587 metadata" one.

**Comment by kif** [comment]
see 587_metadata

**Pull request closed without merging**
