### PR TITLE
Preprocessing in Python, Cython and OpenCL

### PR DESCRIPTION
**Pull request by kif**
Available from the Python interface. Wrapper is still missing but tests are in place.

### CODE REVIEW

**Comment by vallsv** [comment]
In OCL_Preproc it looks to have dup line for every cases
```
+            self.cl_kernel_args["corrections2"][1] = numpy.int8(1)
+            self.cl_kernel_args["corrections2"][1] = numpy.int8(1)
...
+            self.cl_kernel_args["corrections2"][3] = numpy.int8(1)
+            self.cl_kernel_args["corrections2"][3] = numpy.int8(1)
```
It looks strange, maybe it is normal?

**Comment by vallsv** [comment]
- One of the corrections2 is in fact corrections3
- Normalization_factor is missing

**Comment by vallsv** [comment]
```
FAIL: test_cython (pyFAI.test.test_preproc.TestPreproc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\pyfai\venv_test\lib\site-packages\pyFAI\test\test_preproc.py", line 115, in test_cython
    self.one_test(cython_preproc)
  File "C:\projects\pyfai\venv_test\lib\site-packages\pyFAI\test\test_preproc.py", line 101, in one_test
    self.assertGreater(abs(numpy.round(res) - target).max(), 0, "flat != solidangle")
AssertionError: 0.0 not greater than 0 : flat != solidangle
```
I restart the tests

**Comment by vallsv** [comment]
```
FAIL: test_cython (pyFAI.test.test_preproc.TestPreproc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\pyfai\venv_test\lib\site-packages\pyFAI\test\test_preproc.py", line 115, in test_cython
    self.one_test(cython_preproc)
  File "C:\projects\pyfai\venv_test\lib\site-packages\pyFAI\test\test_preproc.py", line 101, in one_test
    self.assertGreater(abs(numpy.round(res) - target).max(), 0, "flat != solidangle")
AssertionError: flat != solidangle
```
I restart the tests, but on windows it looks not very stable

**Comment by kif** [comment]
On Wed, 01 Feb 2017 08:18:43 -0800
Valentin Valls <notifications@github.com> wrote:

> ```
> FAIL: test_cython (pyFAI.test.test_preproc.TestPreproc)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "C:\projects\pyfai\venv_test\lib\site-packages\pyFAI\test\test_preproc.py", line 115, in test_cython
>     self.one_test(cython_preproc)
>   File "C:\projects\pyfai\venv_test\lib\site-packages\pyFAI\test\test_preproc.py", line 101, in one_test
>     self.assertGreater(abs(numpy.round(res) - target).max(), 0, "flat != solidangle")
> AssertionError: flat != solidangle
> ```
> I restart the tests, but on windows it looks not very stable
> 

It may be related to a random value (we use in the flatfield) which
could accidentally be the dummy value.

I will have a look as I noticed myself it failed a couple of times randomly.

Cheers,

**Comment by vallsv** [comment]
Looks fine anyway. Let's merge it.

**Pull request merged**
