### PR TITLE
pilx: Display frame index as plot title

### PR DESCRIPTION
**Pull request by loichuder**
image

### CODE REVIEW

**Comment by EdgarGF93** [comment]
Do we need to take into account the offset of pyFAI-diffmap?
I mean, if there is an offset of 5 points, do they want to see that Frame as 0 or 5?

**Comment by EdgarGF93** [comment]
And I think the correct equation is:
```
image_index = row * map_shape[1] + col
```

If I integrate with pyFAI-diffmap -t 12 -r 3 (12 points fast motor, 3 points slow motor). The last point of the first row (fast-motor) should be 11, 
image

**Comment by loichuder** [comment]
> And I think the correct equation is:
> 
> ```
> image_index = row * map_shape[1] + col
> ```
> 
> since max_shape = [points_slow_motor, points_fast_motor, radial_bins]

Probably. You know this better than me.

> Do we need to take into account the offset of pyFAI-diffmap?

Depends. The frame index is used to index the `/entry_0000/measurement/images_0001` dataset. Is it saved with or without offset ?

**Comment by kif** [comment]
I confirm that:
`image_index = row * map_shape[1] + col + offset`
How is it managed when several input files are provided ?

**Comment by loichuder** [comment]
> How is it managed when several input files are provided ?

It is not managed. I haven't encountered that usecase yet.

**Review by EdgarGF93 — APPROVED** [review]

**Pull request merged**
